sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
stages:
  - test
  - deploy

test:
  provider: script
  script: "mvn install -s ./mvn/ci-settings.xml"
  skip_cleanup: false
  on:
    all_branches: true

deploy:
  provider: script
  script: "mvn deploy -s ./mvn/ci-settings.xml"
  skip_cleanup: true
  condition: "$TRAVIS_TAG = ^v.*$"
  on:
    tags: true
